<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ApplicationIcon>assets\app.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>YuGiOh-MDCoinWatch</AssemblyName>
    <RootNamespace>MdCoinWatch</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <InvariantGlobalization>true</InvariantGlobalization>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <DebugType>none</DebugType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <Version>1.2.0</Version>
    <Product>Yu-Gi-Oh MDCoinWatch</Product>
    <AssemblyTitle>Yu-Gi-Oh MDCoinWatch</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="templates\*.bin" />
    <EmbeddedResource Include="assets\*.bgra" />
    <Compile Remove="legacy\**" />
    <None Remove="legacy\**" />
  </ItemGroup>

</Project>
